image: gcc

stages:
  - build
  - test

packages:
  stage: build
  script:
    - dpkg-query -Wf'${db:Status-abbrev}' python3

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - bin/musique
  stage: test

unit-testing:
  stage: test
  script:
    - make unit-tests

examples_testing:
  stage: test
  script:
    - python3 etc/tools/test.py test examples
