image: gcc

stages:
  - build
  - test

build:
  stage: build
  script:
    - apt-get update && apt-get install -y python3
    - make
  artifacts:
    paths:
      - bin/musique
  stage: test

unit-testing:
  stage: test
  script:
    - make unit-tests
