image: gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

packages:
  stage: build
  script:
    - dpkg-query -Wf'${db:Status-abbrev}' libasound2-dev

build:
  stage: build
  script:
    - (cd lib/midi; make) 
    - make
  artifacts:
    paths:
      - bin/musique

unit-testing:
  stage: test
  script:
    - make unit-tests
