name: musique-build-linux
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Install initial dependencies
        run: "apt update && apt install -y make software-properties-common zip unzip git; add-apt-repository ppa:ubuntu-toolchain-r/test"

      - name: Install build dependencies
        run: "apt install -y gcc-11 g++-11 libasound2-dev"

      - name: Build
        run: "make"
