name: musique-build-and-test
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Install initial dependencies
        run: "sudo apt update && sudo apt install -y make software-properties-common zip unzip git; sudo add-apt-repository ppa:ubuntu-toolchain-r/test"

      - name: Install build dependencies
        run: "sudo apt install -y gcc-11 g++-11 libasound2-dev"

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: "make CC=gcc-11 CXX=g++-11"

      - name: Build unit tests executable
        run: "make mode=unit-test CC=gcc-11 CXX=g++-11"

      - name: Execute unit tests
        run: "bin/linux/unit-test/musique"

      - name: Execute regression tests
        run: "make test CC=gcc-11 CXX=g++-11"

  build-macos:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: "make"

      - name: Execute regression tests
        run: "make test"
